Optimize the python_condaenv_preamble script
Change the preamble script default operation to avoid spending time checking for installed conda and packages

Rename the prefix of all variables to use "PYTHON_CONDAENV_" instead of just "CONDA_"

Rename the prefix of all user-customizable variables to use "PYTHON_CONDAENV_PREAMBLE_"

Add PYTHON_CONDAENV_PREAMBLE_VERBOSE variable to show installation as it occurs.

diff --git a/python/python_condaenv_preamble/python_condaenv_preamble b/python/python_condaenv_preamble/python_condaenv_preamble
--- a/python/python_condaenv_preamble/python_condaenv_preamble
+++ b/python/python_condaenv_preamble/python_condaenv_preamble
@@ -1,14 +1,45 @@
 #!/bin/bash
 # -*-mode: Shell-script; indent-tabs-mode: nil; sh-basic-offset: 2 -*-
 #
+# Python condaenv preamble script -- Install conda, env, and packages and run a .py script
+#
+# User-customizable variables (set them in the environment; see their defaults later on):
+#
+#  PYTHON_CONDAENV_PREAMBLE_CONDA_HEAD_DIR -- Directory above where the miniconda[23] directory
+#    will be installed
+#
+#  PYTHON_CONDAENV_PREAMBLE_CONDA_PYTHON_VERSION -- Identifies Python major version number to
+#    use in the condaenv
+#
+#  PYTHON_CONDAENV_PREAMBLE_REQUIRED_PACKAGES -- Space-separated list of tuples
+#    of the form "import_statement|installer|package_name" that indicate
+#    what packages to install and which installer (pip, conda, etc.) to
+#    use
+#
+#  PYTHON_CONDAENV_INSTALL_CHECK -- When set to 1, idempotently
+#    install the condaenv and the packages listed in the
+#    PYTHON_CONDAENV_PREAMBLE_REQUIRED_PACKAGES variable.
+#
+# PYTHON_CONDAENV_PREAMBLE_VERBOSE -- When set to 1, show the
+#   installation output as it occurs. Otherwise, be silent about the
+#   installation unless an error occurs
+#
 # Example Usage:
 #
-#    # Use a central condaenv for all scripts located in various subdirectories:
-#    PYTHON_CONDAENV_REQUIRED_PACKAGES="import%20matplotlib|conda|matplotlib"
-#    . /the/path/to/the/dir/containing/python_condaenv_preamble "$0" "$@"
+#    #!/bin/bash
+#    export PYTHON_CONDAENV_PREAMBLE_REQUIRED_PACKAGES="import%20matplotlib|conda|matplotlib"
+#    # Only install conda, the env, and packages within the env, when
+#    # PYTHON_CONDAENV_INSTALL_CHECK is set to 1. By default, leave it
+#    # unset to avoid 4 seconds of checking logic each time we invoke the
+#    # script.:
+#    #
+#    #  export PYTHON_CONDAENV_INSTALL_CHECK=1
+#    # 
+#    exec "$(dirname $0)/python_condaenv_preamble" "$0" "$@"
 #
-# The above idempotently ensures that the packages specified by
-# PYTHON_CONDAENV_REQUIRED_PACKAGES are in the conda environment (by
+# Only when PYTHON_CONDAENV_INSTALL_CHECK is set to 1, the above
+# idempotently ensures that the packages specified by
+# PYTHON_CONDAENV_PREAMBLE_REQUIRED_PACKAGES are in the conda environment (by
 # installing them into that environment as needed), and then invokes
 # the .py script that depends upon those packages.
 #
@@ -36,11 +67,28 @@
 #   exec "$(dirname $0)/python_condaenv_preamble" "$0" "$@"
 #
 # have those wrapper scripts just source this script directly. This
-# allows us to maintain a central copy of of the preamble, while
+# allows us to maintain a central copy of the preamble, while
 # having different wrapper scripts and their corresponding .py files
 # located in various subdirectories:
 # ================================================================================
 
+set_log () {
+  if [ "$PYTHON_CONDAENV_PREAMBLE_VERBOSE" = 1 ]
+  then
+    log=/dev/stdout
+  else
+    log=$1
+  fi
+}
+
+cat_log () {
+  if [ "$PYTHON_CONDAENV_PREAMBLE_VERBOSE" = 1 ]
+  then
+    :
+  else
+    cat $log
+  fi
+}
 
 #
 # Install the root conda environment if it does not already exist:
@@ -48,28 +96,35 @@
 #   Each of these variables are overridable by the user, or the
 #   script, to relocate the condaenv:
 #
-CONDA_HEAD_DIR=${CONDA_HEAD_DIR:-$HOME/conda}
-CONDA_PYTHON_VERSION=${CONDA_PYTHON_VERSION:-2}
-CONDA_INSTALL_DIR=${CONDA_INSTALL_DIR:-$CONDA_HEAD_DIR/miniconda$CONDA_PYTHON_VERSION}
+
+PYTHON_CONDAENV_PREAMBLE_CONDA_HEAD_DIR=${PYTHON_CONDAENV_PREAMBLE_CONDA_HEAD_DIR:-$HOME/conda}
+PYTHON_CONDAENV_PREAMBLE_CONDA_PYTHON_VERSION=${PYTHON_CONDAENV_PREAMBLE_CONDA_PYTHON_VERSION:-2}
+CONDA_INSTALL_DIR=$PYTHON_CONDAENV_PREAMBLE_CONDA_HEAD_DIR/miniconda$PYTHON_CONDAENV_PREAMBLE_CONDA_PYTHON_VERSION
 if [ ! -d $CONDA_INSTALL_DIR ]
 then
-  if ! mkdir -p $CONDA_HEAD_DIR
+  if [ "$PYTHON_CONDAENV_INSTALL_CHECK" != 1 ]
   then
-    echo "ERROR: Cannot create $CONDA_HEAD_DIR a directory."
+    echo "ERROR: CONDA_INSTALL_DIR \"$CONDA_INSTALL_DIR\" does not exist as a directory. Set PYTHON_CONDAENV_INSTALL_CHECK=1 and reinvoke to install it."
+    exit 1
+  fi
+
+  if ! mkdir -p $PYTHON_CONDAENV_PREAMBLE_CONDA_HEAD_DIR
+  then
+    echo "ERROR: Cannot create $PYTHON_CONDAENV_PREAMBLE_CONDA_HEAD_DIR a directory."
     exit 1
   fi
   # This name of installer may need to be fiddled with for Mac but this works for Linux:
-  installer=Miniconda${CONDA_PYTHON_VERSION}-latest-$(uname -s)-$(uname -m).sh
-  log=$CONDA_HEAD_DIR/$installer.log
+  installer=Miniconda${PYTHON_CONDAENV_PREAMBLE_CONDA_PYTHON_VERSION}-latest-$(uname -s)-$(uname -m).sh
+  set_log $PYTHON_CONDAENV_PREAMBLE_CONDA_HEAD_DIR/$installer.log
   (
     set -x -e
-    cd $CONDA_HEAD_DIR
+    cd $PYTHON_CONDAENV_PREAMBLE_CONDA_HEAD_DIR
     wget https://repo.continuum.io/miniconda/$installer
     bash ./$installer -b -p $CONDA_INSTALL_DIR
   ) &> $log
   if [ $? != 0 ]
   then
-    cat $log
+    cat_log
     echo
     echo "ERROR: Failed to install root conda environment. See above output for errors."
     exit 1
@@ -87,28 +142,35 @@ export PATH=$CONDA_INSTALL_DIR/bin:$PATH
 CONDA_ENV=${CONDA_ENV:-env1}
 
 #
-# Build the environment given by CONDA_ENV:
+# Optimization: Only do the env existence check if
+# PYTHON_CONDAENV_INSTALL_CHECK is set to 1:
 #
-#   The goal here is to just clone the root environment. Individual
-#   preamble scripts can install whatever packages they need
-#   dynamically via the PYTHON_CONDAENV_REQUIRED_PACKAGES environment
-#   variable.
-#
-env_existence=$(conda info --envs | grep "^$CONDA_ENV ")
-if [ -z "$env_existence" ]
+if [ "$PYTHON_CONDAENV_INSTALL_CHECK" = 1 ]
 then
-  log=$CONDA_HEAD_DIR/conda_create_env.$CONDA_ENV.log
-  (
-    set -x -e
-    cd $CONDA_INSTALL_DIR
-    conda create --name $CONDA_ENV --clone root
-  ) &> $log
-  if [ $? != 0 ]
+  #
+  # Build the environment given by CONDA_ENV:
+  #
+  #   The goal here is to just clone the root environment. Individual
+  #   preamble scripts can install whatever packages they need
+  #   dynamically via the PYTHON_CONDAENV_PREAMBLE_REQUIRED_PACKAGES environment
+  #   variable.
+  #
+  env_existence=$(conda info --envs | grep "^$CONDA_ENV ")
+  if [ -z "$env_existence" ]
   then
-    cat $log
-    echo
-    echo "ERROR: Failed to create condaenv: $CONDA_ENV"
-    exit 1
+    set_log $PYTHON_CONDAENV_PREAMBLE_CONDA_HEAD_DIR/conda_create_env.$CONDA_ENV.log
+    (
+      set -x -e
+      cd $CONDA_INSTALL_DIR
+      conda create --name $CONDA_ENV --clone root
+    ) &> $log
+    if [ $? != 0 ]
+    then
+      cat_log
+      echo
+      echo "ERROR: Failed to create condaenv: $CONDA_ENV"
+      exit 1
+    fi
   fi
 fi
 
@@ -123,64 +185,71 @@ then
 fi
 
 #
-# Detect and install required packages into that condaenv:
+# Optimization: Only do the package installation if
+# PYTHON_CONDAENV_INSTALL_CHECK is set to 1:
 #
-for package_tuple in $PYTHON_CONDAENV_REQUIRED_PACKAGES
-do
+if [ "$PYTHON_CONDAENV_INSTALL_CHECK" = 1 ]
+then
   #
-  # Split on vertical bar:
+  # Detect and install required packages into that condaenv:
   #
-  unset import_package_statement installer package
-  eval $(echo "$package_tuple" | awk -F\| '{ printf ("import_package_statement=\"%s\"; installer=\"%s\"; package=\"%s\"\n", $1, $2, $3); }')
-  if [ -z "$import_package_statement" -o -z "$installer" -o -z "$package" ]
-  then
-    echo "ERROR: PYTHON_CONDAENV_REQUIRED_PACKAGES should be of the form \"import_package_statement1|installer1|package1 import_package_statement2|installer2|package2 ...\""
-    exit 1
-  fi
-
-  exec_statement="import urllib; script = urllib.unquote(\"$import_package_statement\"); exec(script)"
-  if python -c "$exec_statement" &> /dev/null
-  then
-    :
-  else
-    log=$CONDA_HEAD_DIR/install_package.$CONDA_ENV.log.$$
-    (
-      if [ $installer = "pip" ]
-      then
-        pip install --upgrade $package
-      elif [ $installer = "conda" ]
-      then
-        package_existence=$(conda list -n $CONDA_ENV -f $package | grep -v '^#')
-        if [ -z "$package_existence" ]
-        then
-          conda install -y -n $CONDA_ENV $package
-        else
-          conda update -y -n $CONDA_ENV $package
-        fi
-      else
-        echo "ERROR: Invalid installer: \"$installer\""
-        exit 1
-      fi
-    ) &> $log
-    if [ $? != 0 ]
+  for package_tuple in $PYTHON_CONDAENV_PREAMBLE_REQUIRED_PACKAGES
+  do
+    #
+    # Split on vertical bar:
+    #
+    unset import_package_statement installer package
+    eval $(echo "$package_tuple" | awk -F\| '{ printf ("import_package_statement=\"%s\"; installer=\"%s\"; package=\"%s\"\n", $1, $2, $3); }')
+    if [ -z "$import_package_statement" -o -z "$installer" -o -z "$package" ]
     then
-      cat $log
-      echo
-      echo "ERROR: Install of package $package failed. See above."
+      echo "ERROR: PYTHON_CONDAENV_PREAMBLE_REQUIRED_PACKAGES should be of the form \"import_package_statement1|installer1|package1 import_package_statement2|installer2|package2 ...\""
       exit 1
     fi
 
+    exec_statement="import urllib; script = urllib.unquote(\"$import_package_statement\"); exec(script)"
     if python -c "$exec_statement" &> /dev/null
     then
       :
     else
-      cat $log
-      echo
-      echo "ERROR: Install of package $package failed. See above."
-      exit 1
+      set_log $PYTHON_CONDAENV_PREAMBLE_CONDA_HEAD_DIR/install_package.$CONDA_ENV.log.$$
+      (
+        if [ $installer = "pip" ]
+        then
+          pip install --upgrade $package
+        elif [ $installer = "conda" ]
+        then
+          package_existence=$(conda list -n $CONDA_ENV -f $package | grep -v '^#')
+          if [ -z "$package_existence" ]
+          then
+            conda install -y -n $CONDA_ENV $package
+          else
+            conda update -y -n $CONDA_ENV $package
+          fi
+        else
+          echo "ERROR: Invalid installer: \"$installer\""
+          exit 1
+        fi
+      ) &> $log
+      if [ $? != 0 ]
+      then
+        cat_log
+        echo
+        echo "ERROR: Install of package $package failed. See above."
+        exit 1
+      fi
+
+      if python -c "$exec_statement" &> /dev/null
+      then
+        :
+      else
+        cat_log
+        echo
+        echo "ERROR: Install of package $package failed. See above."
+        exit 1
+      fi
     fi
-  fi
-done
+  done
+fi
 
 #
 # Invoke the script:
